version: "3.9"
services:
  api:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/dogegf
    ports: ["3000:3000"]
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dogegf
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
